# Generated by Django 4.1.7 on 2023-03-23 17:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_rating_design'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 23, 17, 11, 24, 800288, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
