# Generated by Django 4.1.7 on 2023-03-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_project_options_project_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='owner',
            new_name='user',
        ),
    ]
