# Generated by Django 4.1.7 on 2023-03-23 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_project_owner_project_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='highlighted',
        ),
    ]
