# Generated by Django 4.1.7 on 2023-03-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_project_highlighted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bye',
            field=models.TextField(null=True),
        ),
    ]
