# Generated by Django 4.1.7 on 2023-03-23 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_project_bye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='bye',
        ),
    ]
