# Generated by Django 4.1.7 on 2023-03-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_project_bye'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
