# Generated by Django 4.1.7 on 2023-03-24 08:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_rating_content_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating_content',
            old_name='user',
            new_name='rating_by',
        ),
        migrations.AlterUniqueTogether(
            name='rating_content',
            unique_together={('rating_by', 'project')},
        ),
        migrations.AlterIndexTogether(
            name='rating_content',
            index_together={('rating_by', 'project')},
        ),
    ]
